Bibliotheek/Controllers/BookController.cs
#region

using System.Web;
using Bibliotheek.Attributes;
using Bibliotheek.Models;
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

#endregion

namespace Bibliotheek.Controllers
{
    public class BookController : Controller
    {
        #region Public Methods

        // GET: Book 
        [EnableCompression]
        public ActionResult AddBook()
        {
            // Redirect is the user isn't an admin 
            if (!IdentityModel.CurrentUserAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = BindModel(new BookModel());

            return View(model);
        }

        // POST: Book 
        [HttpPost]
        [EnableCompression]
        public ActionResult AddBook(BookModel model)
        {
            // Redirect is the user isn't an admin 
            if (!IdentityModel.CurrentUserAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Error = String.Empty;
            model = BindModel(model);

            if (!ModelState.IsValid) return View(model);
            if (model.AddBook())
            {
                ViewBag.Error = "Het boek is toegevoegd!";
                return View(model);
            }
            ViewBag.Error = "Het boek is niet toegevoegd, probeer het later nog eens!";
            return View(model);
        }

        // GET: AllBooks 
        [EnableCompression]
        public ActionResult AllBooks()
        {
            return View();
        }

        // GET: Genre 
        [EnableCompression]
        public ActionResult Genre(string genre)
        {
            return View();
        }

        // GET: SearchBooks 
        [EnableCompression]
        public ActionResult SearchBooks(string searchTerm)
        {
            return View();
        }

        // GET: SingleAuthor 
        [EnableCompression]
        public ActionResult SingleAuthor(string name)
        {
            return View();
        }

        // GET: SingleBook 
        [EnableCompression]
        public ActionResult SingleBook(string id)
        {
            return View();
        }

        #endregion Public Methods

        #region Private Methods

        private static BookModel BindModel(BookModel model)
        {
            var genreTypes = Enum.GetValues(typeof (BookModel.BookGenres)).Cast<BookModel.BookGenres>();
            model.Genres = from genre in genreTypes
                select new SelectListItem
                {
                    Text = BookModel.DictGenre[genre],
                    Value = ((int) genre).ToString(CultureInfo.InvariantCulture)
                };

            var floorTypes = Enum.GetValues(typeof (BookModel.BookFloors)).Cast<BookModel.BookFloors>();
            model.Floors = from floor in floorTypes
                select new SelectListItem
                {
                    Text = BookModel.DictFloors[floor] + " verdieping" + " book",
                    Value = ((int) floor).ToString(CultureInfo.InvariantCulture)
                };

            var rackTypes = Enum.GetValues(typeof (BookModel.BookRacks)).Cast<BookModel.BookRacks>();
            model.Racks = from rack in rackTypes
                select new SelectListItem
                {
                    Text = BookModel.DictRacks[rack] + " rek" + " book",
                    Value = ((int) rack).ToString(CultureInfo.InvariantCulture)
                };

            return model;
        }

        #endregion Private Methods
    }
}

Bibliotheek/Controllers/LoggedController.cs
#region

using Bibliotheek.Attributes;
using System.Web.Mvc;
using System.Web.Security;

#endregion

namespace Bibliotheek.Controllers
{
    public class LoggedController : Controller
    {
        #region Public Methods

        // GET: Logged 
        public ActionResult Account()
        {
            // Redirect if the user isn't logged in 
            if (!System.Web.HttpContext.Current.Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        //
        // GET: /Logged/LoggedIn 
        [EnableCompression]
        public ActionResult LoggedIn()
        {
            // Redirect if the user isn't logged in 
            if (!System.Web.HttpContext.Current.Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        //
        // GET: /Logged/SignOut 
        [EnableCompression]
        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();

            return View();
        }

        #endregion Public Methods
    }
}

Bibliotheek/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using Bibliotheek.Models
<!doctype html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en-US">
    <!--<![endif]-->
    <head>
        <!-- META TAGS -->
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>
        <link rel="shortcut icon" href="~/Images/favicon.png" />
        <!-- Google Web Fonts-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <!-- Style Sheet-->
        @Styles.Render("~/Bundles/CommonStyles")
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="~/Js/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- Start of Header -->
        <div class="header-wrapper">
            <header>
                <div class="container">
                    <!-- Start of Main Navigation -->
                    <nav class="main-nav">
                        <div class="menu-top-menu-container">
                            <ul id="menu-top-menu" class="clearfix">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("Over ons", "About", "Home")</li>
                                @{
                                    if (!IdentityModel.CurrentUserLoggedIn)
                                    {
                                        <li>@Html.ActionLink("Alle boeken", "AllBooks", "Book")</li>
                                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                                    }
                                    else
                                    {
                                        <li>@Html.ActionLink("Account", "Account", "Logged")</li>
                                        if (IdentityModel.CurrentUserAdmin)
                                        {
                                            <li>
                                                <a href="#">Gebruikers</a>
                                                <ul class="sub-menu">
                                                    <li>@Html.ActionLink("Gebruiker toevoegen", "NewAccount", "Account")</li>
                                                    <li>@Html.ActionLink("Alle gebruikers", "AllAccounts", "Account")</li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Boeken</a>
                                                <ul class="sub-menu">
                                                    <li>@Html.ActionLink("Alle boeken", "AllBooks", "Book")</li>
                                                    <li>@Html.ActionLink("Boek toevoegen", "AddBook", "Book")</li>
                                                </ul>
                                            </li>
                                        }
                                        else
                                        {
                                            <li>@Html.ActionLink("Alle boeken", "AllBooks", "Book")</li>
                                        }
                                    }
}
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                @{
                                    if (IdentityModel.CurrentUserLoggedIn)
                                    {
                                        <li>@Html.ActionLink("Uitloggen", "SignOut", "Logged")</li>
                                    }
                                }
                            </ul>
                        </div>
                    </nav>
                    <!-- End of Main Navigation -->
                </div>
            </header>
        </div>
        <!-- End of Header -->
        <!-- Start of Search Wrapper -->
        <div class="search-area-wrapper">
            <div class="search-area container">
                <h3 class="search-header">De Bibliotheek</h3>
                <!--<p class="search-tag-line">Zoekt u een boek? Typ hieronder de titel of auteur!</p>

                <form id="search-form" class="search-form clearfix" action="#" autocomplete="off">
                    <input class="search-term required" type="text" id="s" name="s" placeholder="Typ hier een boektitel of auteur" title="* Typ een zoekterm!" />
                    <input class="search-btn" type="submit" value="Search" />
                    <div id="search-error-container"></div>
                </form>-->
            </div>
        </div>
        <!-- End of Search Wrapper -->
        <!-- Start of Page Container -->
        <div class="page-container">
            <div class="container">
                <div class="row">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- End of Page Container -->
        <!-- Start of Footer -->
        <footer id="footer-wrapper">
            <div id="footer" class="container">
                <div class="row">
                    <div class="span6">
                        <section class="widget">
                            <h3 class="title">Lorem ipsum</h3>
                            <div class="textwidget">
                                <p>dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. </p>
                                <p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. </p>
                            </div>
                        </section>
                    </div>
                    <div class="span6">
                        <section class="widget">
                            <h3 class="title">Flickr Foto's</h3>
                            <div class="flickr-photos" id="bibliotheekrotterdam">
                            </div>
                        </section>
                    </div>
                </div>
            </div>
            <!-- end of #footer -->
            <!-- Footer Bottom -->
            <div id="footer-bottom-wrapper">
                <div id="footer-bottom" class="container">
                    <div class="row">
                        <div class="span6">
                            <p class="copyright">
                                Copyright &copy; @DateTime.Now.Year. Owain van Brakel
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Footer Bottom -->
        </footer>
        <!-- End of Footer -->
        <a href="#top" id="scroll-top"></a>
        <!-- script -->
        @Scripts.Render("~/Bundles/CommonScripts")
        @RenderSection("scripts", false)
    </body>
</html>

Bibliotheek/Views/Shared/_NewBook.cshtml
@using Bibliotheek.Models
<section class="widget">
    <h3 class="title">
        Laatste boeken
    </h3>
    <ul class="articles">
        @{
            var book = BookModel.GetNewBooks();
            var random = new Random();

            for (var i = 1; i <= book.Count / 5; i++)
            {
                <li class="article-entry standard">
                    <h4>@Html.ActionLink(book[i * 5 - 4], "SingleBook", "Book", new { id = book[i * 5 - 5] }, null) - @Html.ActionLink(book[i * 5 - 3], "SingleAuthor", "Book", new { name = book[i * 5 - 3] }, null) </h4>
                    <span class="article-meta"> @book[i * 5 - 1] in @Html.ActionLink(BookModel.DictGenreFromInt[Convert.ToInt16(book[i * 5 - 2])], "Genre", "Book", new { genre = book[i * 5 - 2] }, null)</span>
                    <span class="like-count"> @random.Next(100) </span>
                </li>
            }
        }
    </ul>
</section>